# Generated by Django 3.0.3 on 2020-06-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tel',
            field=models.CharField(blank=True, default=0, max_length=12),
            preserve_default=False,
        ),
    ]
