# Generated by Django 2.2.1 on 2019-12-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20191030_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeBeans',
            fields=[
                ('beansCode', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('beansName', models.CharField(max_length=25)),
                ('place', models.CharField(max_length=25)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
