# Generated by Django 2.2.1 on 2019-12-08 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0003_coffeebeans'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=25)),
            ],
        ),
        migrations.RenameField(
            model_name='coffeebeans',
            old_name='beansName',
            new_name='beans_name',
        ),
        migrations.RenameField(
            model_name='coffeebeans',
            old_name='createDate',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='insertregister',
            old_name='userId',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='coffeebeans',
            name='beansCode',
        ),
        migrations.AddField(
            model_name='coffeebeans',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coffeebeans',
            name='stock',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(blank=True, null=True)),
                ('buy_date', models.DateTimeField(auto_now_add=True)),
                ('payment_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.PaymentMethod')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id', 'user_name')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_code', models.CharField(max_length=5)),
                ('selling_price', models.IntegerField()),
                ('beans_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.CoffeeBeans')),
                ('purchase_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.PurchaseHistory')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('purchase_code', 'user_name', 'detail_code')},
            },
        ),
    ]
