# Generated by Django 2.2.5 on 2020-03-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20191209_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeebeans',
            name='beans_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
