# Generated by Django 3.0.3 on 2020-04-14 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20200414_1947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InsertRegister',
        ),
        migrations.AddField(
            model_name='coffeebeans',
            name='place_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='market.PlaceCategory'),
            preserve_default=False,
        ),
    ]
