# Generated by Django 3.0.3 on 2020-04-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_remove_coffeebeans_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placecategory',
            name='place',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
