# Generated by Django 3.0.3 on 2020-04-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_auto_20200423_1137'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartinfo',
            constraint=models.UniqueConstraint(fields=('user_id', 'coffee_beans'), name='unique_cart'),
        ),
    ]
