# Generated by Django 3.0.3 on 2020-04-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_auto_20200423_1205'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartinfo',
            name='unique_cart',
        ),
        migrations.AddConstraint(
            model_name='cartinfo',
            constraint=models.UniqueConstraint(fields=('user', 'coffee_beans'), name='unique_cart'),
        ),
    ]
