# Generated by Django 3.0.3 on 2020-05-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_auto_20200423_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeansImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beans_image', models.ImageField(upload_to='market/')),
            ],
        ),
    ]
