# Generated by Django 3.0.3 on 2020-05-06 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_beansimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeebeans',
            name='beans_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.BeansImage'),
        ),
    ]
