# Generated by Django 3.0.3 on 2020-05-12 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_auto_20200508_1707'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchasedetail',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='detail_code',
        ),
        migrations.RemoveField(
            model_name='purchasedetail',
            name='user_name',
        ),
    ]
